/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package gradletest1

import org.apache.velocity.app.Velocity
import org.apache.velocity.VelocityContext
import org.apache.velocity.Template
import org.apache.velocity.app.VelocityEngine

/**
 * App class
 */
class App {

    void exercise(String templateDir, String templateName) {

        /* lets make a Context and put data into it */
        VelocityContext context = new VelocityContext()
        context.put('name', 'Velocity')
        context.put('project', 'Jakarta')

        /* Create an engine */
        VelocityEngine engine = new VelocityEngine()
        Properties props = new Properties()
        props.setProperty("file.resource.loader.path", templateDir)
        engine.init(props)

        /* Render a template */
        StringWriter w = new StringWriter()
        Template template = engine.getTemplate(templateName)
        template.merge(context, w)
        println(' template : ' + w)

        /* lets make our own string to render */
        String s = 'We are using $project $name to render this.'
        w = new StringWriter()
        engine.evaluate(context, w, 'mystring', s)
        println(' string : ' + w)
    }

    static void main(String[] args) {
        if (args.length == 2) {
            new App().exercise(args[0], args[1])
        } else {
            println("Error: $args.length arguments provided")
        }
    }
}
